# Generated by Django 4.1.4 on 2022-12-20 22:08

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_sco_nom', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Etu_classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_nom', models.CharField(max_length=25)),
                ('ann_sco', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etu', models.CharField(max_length=25)),
                ('nni_etu', models.CharField(max_length=25)),
                ('dt_nai_etu', models.DateField()),
                ('dt_iscri_etu', models.DateField()),
                ('fraisInsc_etu', models.CharField(max_length=25)),
                ('sexe_etu', models.CharField(max_length=25)),
                ('fraisFixe_etu', models.CharField(max_length=25)),
                ('image_etu', models.ImageField(blank=True, null=True, upload_to=App.models.get_name)),
                ('classe_etu', models.CharField(max_length=25)),
                ('an_sco', models.CharField(max_length=25)),
                ('nom_ag', models.CharField(default='', max_length=25)),
                ('num_ag', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
