# Generated by Django 4.1.4 on 2022-12-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='nom_ag',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='num_ag',
            field=models.CharField(default='', max_length=30),
        ),
    ]
