# Generated by Django 4.1.4 on 2022-12-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_num_ag_etudiant_conn_ag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salair_emp', models.IntegerField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='etu_classe',
            name='class_nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='fraisFixe_etu',
            field=models.IntegerField(max_length=25),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='fraisInsc_etu',
            field=models.IntegerField(max_length=25),
        ),
    ]
