# Generated by Django 4.1.4 on 2022-12-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_employe_salair_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='fraisFixe_etu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='fraisInsc_etu',
            field=models.IntegerField(default=0),
        ),
    ]
