# Generated by Django 4.1.4 on 2022-12-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_etudiant_fraisfixe_etu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='credit_emp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employe',
            name='fonc_emp',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='employe',
            name='nni_emp',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='employe',
            name='nom_emp',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='employe',
            name='num_tel_emp',
            field=models.CharField(default='', max_length=15),
        ),
    ]
