# Generated by Django 4.1.4 on 2022-12-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_employe_credit_emp_employe_fonc_emp_employe_nni_emp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
