# Generated by Django 4.1.4 on 2022-12-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_employe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
