# Generated by Django 4.1.4 on 2023-01-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_employe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etu', models.CharField(max_length=25)),
                ('prix', models.IntegerField()),
                ('dt_pay', models.DateField()),
                ('ann_sco', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
