# Generated by Django 4.1.4 on 2023-01-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_frais'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frais',
        ),
    ]
