# Generated by Django 4.1.4 on 2023-01-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_etudiant_nbrpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDep', models.DateField()),
                ('naturDep', models.CharField(max_length=50)),
                ('montanDep', models.IntegerField(default=0)),
            ],
        ),
    ]
